spring:
  application:
    name: vehicle-track-service
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672} 
    username: ${RABBIT_MQ_USER:swedqmq}
    password: ${RABBIT_MQ_PASSWORD:swedqmq}
    listener:
      simple:
        concurrency: 3
        max-concurrency: 6
queue:
  vehicle:
    track:
      name: VehicleTrackQueue 
server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka/
br:
  com:
    danilopaixao:
      service:
        vehicle:
          protocol: http 
          host: vehicle-service
          version: v1