spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization:      write-dates-as-timestamps: false
      WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: vehicle-track-service
  rabbitmq:
    addresses: ${RABBIT_MQ_ADDRESS:chimpanzee.rmq.cloudamqp.com/zcdpcvpk}
    port: ${RABBIT_MQ_PORT:5672} 
    username: ${RABBIT_MQ_USER:zcdpcvpk}
    password: ${RABBIT_MQ_PASSWORD:jYbSUveUBNCCYhXqYQg9OXDuLqaZe4Kr}
    listener:
      simple:
        concurrency: 3
        max-concurrency: 6
  redis:
    port: ${REDIS_PORT:10508}
    host: ${REDIS_HOST:redis-10508.c9.us-east-1-4.ec2.cloud.redislabs.com}
    password: ${REDIS_PASSWORD:aH9WHGiUkpBOoZHF46kciNl1p6eNirEW}
    jedis:      pool:        max-active: 10
queue:
  vehicle:
    track:
      name: ${VEHICLE_TRACK_QUEUE:VehicleTrackQueue} 
server:
  port: 8080
eureka:
  client:
    enabled: ${EUREKA_ENABLE:false}
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka/
br:
  com:
    danilopaixao:
      vehicle:
        track:
          secondstooffline: 60
      validator:
        timelimiteminutes: 240 
      service:
        vehicle:
          url: ${VEHICLE_SERVICE_URL:http://vehicle-service/v1/}