version: '2'
services:
    vehicle-track:
        container_name: vehicle-track
        build:
            dockerfile: ./vehicle.track.dockerfile
            context: .
        environment:
            - REDIS_HOST=redisdb
            - REDIS_PORT=6379
            - REDIS_PASSWORD=123456
            - RABBIT_MQ_ADDRESS=rabbitmq
            - RABBIT_MQ_USER=admin
            - RABBIT_MQ_PASSWORD=123456
            - RABBIT_MQ_PORT=5672
            - VEHICLE_TRACK_QUEUE=VehicleTrackQueue
            - EUREKA_SERVER=eureka-server
            - EUREKA_PORT=8761
            - ENABLED_EUREKA=true
            - VEHICLE_SERVICE_URL=http://vehicle-service/v1/
        ports:
            - 8080:8084
        networks:
            - microservice-network
networks: 
    microservice-network:
        driver: bridge